DROP USER VMS CASCADE;

CREATE USER VMS
  IDENTIFIED BY vms
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  -- 2 Roles for VMS 
  GRANT CONNECT TO VMS;
  GRANT RESOURCE TO VMS;
  ALTER USER VMS DEFAULT ROLE ALL;

  -- 3 System Privileges for VMS 
  GRANT CREATE PROCEDURE TO VMS;
  GRANT CREATE VIEW TO VMS;
  GRANT UNLIMITED TABLESPACE TO VMS;
