drop table VMS.MANCHU_VERB_STEM;

CREATE TABLE VMS.MANCHU_VERB_STEM (
 ID NUMBER,
 STEM VARCHAR2(70),
 TRANSLATION VARCHAR2(500)
);

ALTER TABLE VMS.MANCHU_VERB_STEM ADD PRIMARY KEY( ID );

CREATE INDEX IX_MCH_VERB_STEM ON VMS.MANCHU_VERB_STEM ( STEM);


INSERT INTO VMS.MANCHU_VERB_STEM ( ID, STEM, TRANSLATION )
 SELECT ID, substr( d.word ,1, length( d.word)-3 ), translation
  FROM VMS.MANCHU_DICT_JOIN d
  WHERE d.word like '%MBI';
  
  COMMIT;
  
  