  
  CREATE TABLE VMS.MANCHU_VERB_SUFFIX ( ID NUMBER, SUFFIX VARCHAR2(20), DESCRIPTION varchar2(100) );
  
  
  CREATE SEQUENCE seq_mch_verb_suffix;

CREATE OR REPLACE TRIGGER trg_mch_verb_siffix
BEFORE INSERT ON VMS.manchu_verb_suffix
FOR EACH ROW
BEGIN
 SELECT seq_mch_verb_suffix.NEXTVAL INTO :NEW.id FROM dual;
END;



ALTER TABLE VMS.MANCHU_VERB_SUFFIX ADD PRIMARY KEY( ID );

CREATE INDEX IX_MCH_VERB_SUFFIX ON VMS.MANCHU_VERB_SUFFIX ( SUFFIX );
